import calendar
year=2025
print(calendar.calendar(year))
year=2026
print(calendar.calendar(year))
year=2027
print(calendar.calendar(year))
year=2028
print(calendar.calendar(year))
year=2029
print(calendar.calendar(year))
year=2030
print(calendar.calendar(year))
year=2031
print(calendar.calendar(year))
year=2032
print(calendar.calendar(year))
year=2033
print(calendar.calendar(year))
year=2034
print(calendar.calendar(year))
year=2035
print(calendar.calendar(year))
year=2036
print(calendar.calendar(year))
year=2037
print(calendar.calendar(year))
year=2038
print(calendar.calendar(year))
year=2039
print(calendar.calendar(year))
year=2040
print(calendar.calendar(year))
year=2041
print(calendar.calendar(year))
year=2042
print(calendar.calendar(year))
year=2043
print(calendar.calendar(year))
year=2044
print(calendar.calendar(year))
year=2045
print(calendar.calendar(year))
year=2046
print(calendar.calendar(year))
year=2047
print(calendar.calendar(year))
year=2048
print(calendar.calendar(year))
year=2049
print(calendar.calendar(year))
year=2050
print(calendar.calendar(year))